### PR TITLE
add showBrowser config option to print browser for each spec

### PR DESCRIPTION
**Pull request by squarebracket**
Simple PR to append the browser name to the spec name if desired.

### CODE REVIEW

**Comment by joeyparrish** [comment]
@tmcgee123, can you please take a look at this?  I was about to file an issue asking for this same feature.  When running tests on a large Selenium grid, it is critical to know which browser reported which failure.

**Comment by tmcgee123** [comment]
Sorry for the delay. Thank you for your contribution!

**Comment by tmcgee123** [comment]
> @tmcgee123, can you please take a look at this? I was about to file an issue asking for this same feature. When running tests on a large Selenium grid, it is critical to know which browser reported which failure.

Sorry for the delay. The changes should now be available when you update to the latest package via npm.

Cheers!

**Comment by joeyparrish** [comment]
That's wonderful, thank you so much!  I was about to update my project to point to a fork while I waited for that.

From my limited perspective, it's no delay at all.  I only found the PR in a search earlier this morning.  😁

**Pull request merged**
